---
- name: Deploy Windows Server AD
  hosts: winserver
  become: false
  gather_facts: false

  tasks:
  - name: Ensure AD timezone matches IPA timezone.
    community.windows.win_timezone:
      timezone: "{{ winserver_timezone }}"

  - name: Change the Window hostname
    ansible.windows.win_hostname:
      name: "server"
    register: hostname

  - name: Disable ms_tcpip6 for all Interfaces
    community.windows.win_net_adapter_feature:
      interface: '*'
      state: disabled
      component_id:
      - ms_tcpip6

  - name: Reboot server
    ansible.windows.win_reboot:
      msg: "Reboot after name and timezone changes."
      pre_reboot_delay: 15
    when: hostname.reboot_required

  - name: Install AD feature
    ansible.windows.win_feature:
      name: AD-Domain-Services
      include_management_tools: true
      include_sub_features: true
      state: present

  - name: Install DNS feature and configure first AD Domain
    microsoft.ad.domain:
      install_dns: true
      dns_domain_name: "{{ winserver_domain }}"
      domain_netbios_name: "{{ winserver_netbios_name }}"
      safe_mode_password: "{{ winserver_dsrm_password }}"
      reboot: true

  - name: Add IPA DNS forward zone
    ansible.windows.win_shell: 'Add-DnsServerConditionalForwarderZone -Name "{{ ipaserver_domain }}" -MasterServers {{ ipaserver_ip }}'
    register: result
    failed_when: result.failed and "ResourceExists" not in result.stderr
    changed_when: not result.failed

  - name: Add jdoe test user.
    microsoft.ad.user:
      # 'name'' will be the user SAM account name and identity.
      name: jdoe
      firstname: John
      surname: Doe
      upn: "jdoe@{{ winserver_domain }}"
      enabled: true
      password_expired: false
      password: SomeUS3Rpassword
      update_password: on_create
      state: present
