---
- name: Pre-checks to deploy IPA
  hosts: ipaserver
  become: true
  gather_facts: false

  tasks:
  - name: Set FQDN for FreeIPA server
    ansible.builtin.hostname:
      name: "{{ ipaserver_hostname }}"

  - name: Ensure IPA timezone matches AD timezone.
    community.general.timezone:
      name: "{{ ipaserver_timezone }}"

# ---------------------
- name: Deploy IPA with support to AD.
  hosts: ipaserver
  become: false
  gather_facts: true

  roles:
  - role: ipaserver
    state: present
    become: true

  # IPA configuration of trust to Windows AD
  tasks:
  - name: Add forward to AD server
    ipadnsconfig:
      ipaadmin_password: SomeADMINpassword
      forwarders:
      - ip_address: "{{ winserver_ip }}"
      forward_policy: "only"
...
