---
- name: Add user with AD administrator
  hosts: ipaserver
  become: false
  gather_facts: false

  tasks:
  - name: Add user with AD administrator principal
    ipauser:
      ipaadmin_password: SomeW1Npassword
      ipaadmin_principal: administrator@ad.ipa.test
      name: some_user
      first: some
      last: user
...
